---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonemanage
  labels:
    app: phonemanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonemanage
  template:
    metadata:
      labels:
        app: phonemanage
    spec:
      containers:
        - name: phonemanage
          image: username/phonemanage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq
  labels:
    app: mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
        - name: mq
          image: username/mq:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: phonemanage
  labels:
    app: phonemanage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: phonemanage


---


apiVersion: v1
kind: Service
metadata:
  name: mq
  labels:
    app: mq
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mq

